### ISSUE TITLE
Safer, more consistent uninitialized values

### ISSUE THREAD

**Issue by KNiewiadomski-uAvionics** [UAVCAN/dsdl#37]
Hi
We are trying to use UAVCAN (libcanard) in our project. We found some inconsistency with uavcan.equipment.safety message - most of other messages uses 0 for nominal state and all bits set to indicate error (uavcan.protocol.NodeStatus.health - 0b00 for HEALTH_OK, 0b11 for HEALTH_CRITICAL, etc.). The same is valid for undefined values (maximum value for unsigned integer, NaN for float (in both cases all bits set to 1)). For uavcan.equipment.safety message this approach results in FULLY_ARMED as default value. 

I propose:

```
#
# This message represents the system arming status.
# Some nodes may refuse to operate unless the system is fully armed.
#

uint8 STATUS_DISARMED           = 0
uint8 STATUS_FULLY_ARMED        = 254
uint8 STATUS_MALFUNCTION = 255 # or STATUS_CRASHED

uint8 status
```

Or to flip values to 0 = FULLY_ARMED and 255 = DISARMED

We are trying to initialize all our UAVCAN buffers and structs with 0xFF to make it more "errorproof" by setting it to safe, detectable, bug indicating default value (e.g. 127%).

**Comment by pavel-kirienko** [comment]
Thanks, @KNiewiadomski-uAvionics!

I am reluctant to introduce a breaking change just for the sake of a minor security improvement. Perhaps you could choose a different memory initialization pattern or apply some other practices of defensive programming?

The fact that other values use all-set bits to indicate errors was not entirely intentional.
